{{- range list .Values.authorization .Values.organization .Values.marketplace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .name }}-{{ .env }} | default {{ .name }}"
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ .name }}
    env: {{ .env | default "prd" }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
      env: {{ .env | default "prd" }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        env: {{ .env | default "prd" }}
    spec:
      volumes:
        - name: properties
          configMap:
            name: {{ .name }}-properties
      #   - name: configfiles
      #     secret:
      #         # This must match the name of your secret above
      #         secretName: azure-pgbouncer-config
      nodeSelector:
        envnode: test
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred-azure
        - name: regcred-gitlab
      terminationGracePeriodSeconds: 320
      containers:
        - envFrom:
            - configMapRef:
                name: {{ .name }}
            - configMapRef:
                name: {{ .name }}-properties
          name: {{ .name }}
          image: {{ .name }}:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8000
              name: debug
              protocol: TCP
          volumeMounts:
            - name: properties
              mountPath: /usr/src/empower/config/application.properties
              subPath: application.properties
          lifecycle:
            preStop:
              exec:
                command:
                - sleep
                - "190"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 250
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 250
            periodSeconds: 15
            successThreshold: 2
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 250m
              memory: 250M
{{- end }}